version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=translated_chat

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=translated_chat
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql